# -*- coding: utf8 -*-
ROLE_STARTUP = 0
ROLE_PROGRAMMER = 1
ROLE_SEO = 2
ROLE_INVESTOR = 3

STUDY_PRICE = 10
STUDY_EXPERIENCE = 10

JOB_MULTIPLIER = 3

OUTSOURCE_PRICE = 10
OUTSOURCE_EXPERIENCE = 10

FAME_MULTIPLIER = 10
PENALTY_MULTIPLIER = 10

TAX_MULTIPLIER = 0.13
